// server/src/db/seedData.ts

export const seedData = {
  organization: {
    id: 'org-apex-001',
    name: 'Apex Industrial Systems Corp.',
    industry: 'Heavy Manufacturing, Advanced Materials & Specialty Chemicals',
    countries: ['DE', 'US', 'BE', 'JP'],
    createdAt: new Date('2023-01-01T00:00:00Z').toISOString(),
    updatedAt: new Date().toISOString(),
  },
  users: [
    {
      id: 'usr-apex-001',
      organizationId: 'org-apex-001',
      email: 'owner@apexindustrial.com',
      passwordHash: '$2b$10$vI8aWBnW3fID.ZQ4/ZO1e.uKzVfE7yUOzLzV2y4d42mHek3uX44qK', // Password123!
      fullName: 'Marcus Vance',
      role: 'OWNER',
    },
    {
      id: 'usr-apex-002',
      organizationId: 'org-apex-001',
      email: 'elena.rostova@apexindustrial.com',
      passwordHash: '$2b$10$vI8aWBnW3fID.ZQ4/ZO1e.uKzVfE7yUOzLzV2y4d42mHek3uX44qK', // Password123!
      fullName: 'Elena Rostova',
      role: 'ADMIN',
    },
    {
      id: 'usr-apex-003',
      organizationId: 'org-apex-001',
      email: 'sarah.lin@apexindustrial.com',
      passwordHash: '$2b$10$vI8aWBnW3fID.ZQ4/ZO1e.uKzVfE7yUOzLzV2y4d42mHek3uX44qK', // Password123!
      fullName: 'Sarah Lin',
      role: 'COMPLIANCE_MANAGER',
    },
    {
      id: 'usr-apex-004',
      organizationId: 'org-apex-001',
      email: 'david.richter@apexindustrial.com',
      passwordHash: '$2b$10$vI8aWBnW3fID.ZQ4/ZO1e.uKzVfE7yUOzLzV2y4d42mHek3uX44qK', // Password123!
      fullName: 'David Richter',
      role: 'LEGAL_REVIEWER',
    },
    {
      id: 'usr-apex-005',
      organizationId: 'org-apex-001',
      email: 'tariq.analyst@apexindustrial.com',
      passwordHash: '$2b$10$vI8aWBnW3fID.ZQ4/ZO1e.uKzVfE7yUOzLzV2y4d42mHek3uX44qK', // Password123!
      fullName: 'Tariq Al-Mansoor',
      role: 'ANALYST',
    },
    {
      id: 'usr-apex-006',
      organizationId: 'org-apex-001',
      email: 'chloe.viewer@apexindustrial.com',
      passwordHash: '$2b$10$vI8aWBnW3fID.ZQ4/ZO1e.uKzVfE7yUOzLzV2y4d42mHek3uX44qK', // Password123!
      fullName: 'Chloe Bennett',
      role: 'VIEWER',
    },
  ],
  jurisdictions: [
    { id: 'jur-eu', code: 'EU', name: 'European Union', country: 'European Union', region: 'Europe', latitude: 50.8503, longitude: 4.3517 },
    { id: 'jur-us', code: 'US', name: 'United States (Federal)', country: 'United States', region: 'North America', latitude: 38.9072, longitude: -77.0369 },
    { id: 'jur-us-ca', code: 'US-CA', name: 'State of California', country: 'United States', region: 'North America (West)', latitude: 38.5816, longitude: -121.4944 },
    { id: 'jur-de', code: 'DE', name: 'Federal Republic of Germany', country: 'Germany', region: 'Europe', latitude: 52.5200, longitude: 13.4050 },
    { id: 'jur-be', code: 'BE', name: 'Kingdom of Belgium (Flanders)', country: 'Belgium', region: 'Europe', latitude: 51.2194, longitude: 4.4025 },
    { id: 'jur-jp', code: 'JP', name: 'Japan (METI & MOE)', country: 'Japan', region: 'Asia-Pacific', latitude: 35.6762, longitude: 139.6503 },
    { id: 'jur-uk', code: 'UK', name: 'United Kingdom', country: 'United Kingdom', region: 'Europe', latitude: 51.5074, longitude: -0.1278 },
    { id: 'jur-intl', code: 'INTL', name: 'International Environmental Pacts', country: 'Global', region: 'Global', latitude: 46.2044, longitude: 6.1432 },
  ],
  facilities: [
    {
      id: 'fac-001',
      organizationId: 'org-apex-001',
      name: 'Apex Advanced Materials — Dresden',
      country: 'Germany',
      location: 'Silicon Saxony TechPark, Dresden, Saxony, Germany',
      latitude: 51.0504,
      longitude: 13.7373,
      facilityType: 'Chemical Synthesis & Specialty Fluoropolymer Plant',
      productionCapacity: '45,000 MT / annum',
      emissionsData: { scope1_co2e_mt: 12400, scope2_co2e_mt: 8900, scope3_co2e_mt: 34200, voc_emissions_kg: 840, nox_kg: 450 },
      waterUsage: { annual_m3: 185000, recycling_rate_pct: 78.4, discharge_purity_pct: 99.1 },
      energyMetrics: { mwh_consumed: 38400, renewable_pct: 62.0, ppa_contracts: ['Vattenfall Wind 20MW'] },
      wasteOutput: { hazardous_waste_mt: 310, non_hazardous_waste_mt: 1250, landfill_diversion_pct: 94.2 },
      processes: ['proc-001', 'proc-002', 'proc-008', 'proc-009'],
    },
    {
      id: 'fac-002',
      organizationId: 'org-apex-001',
      name: 'Apex BioPlastics & Packaging — Austin',
      country: 'United States',
      location: 'Met Center Industrial Blvd, Austin, TX, USA',
      latitude: 30.2672,
      longitude: -97.7431,
      facilityType: 'Advanced Polymer Extrusion & Bio-Resin Formulation',
      productionCapacity: '60,000 MT / annum',
      emissionsData: { scope1_co2e_mt: 8200, scope2_co2e_mt: 14500, scope3_co2e_mt: 48900, voc_emissions_kg: 320, nox_kg: 210 },
      waterUsage: { annual_m3: 92000, recycling_rate_pct: 85.0, discharge_purity_pct: 99.8 },
      energyMetrics: { mwh_consumed: 42100, renewable_pct: 48.5, solar_onsite_mw: 3.2 },
      wasteOutput: { hazardous_waste_mt: 45, non_hazardous_waste_mt: 890, landfill_diversion_pct: 98.1 },
      processes: ['proc-005', 'proc-006', 'proc-008', 'proc-014'],
    },
    {
      id: 'fac-003',
      organizationId: 'org-apex-001',
      name: 'Apex Chemical Refineries — Antwerp',
      country: 'Belgium',
      location: 'Port of Antwerp-Bruges Chemical Cluster, Antwerp, Belgium',
      latitude: 51.2194,
      longitude: 4.4025,
      facilityType: 'Petrochemical Distillation & Industrial Solvent Purification',
      productionCapacity: '120,000 MT / annum',
      emissionsData: { scope1_co2e_mt: 38900, scope2_co2e_mt: 22100, scope3_co2e_mt: 98000, voc_emissions_kg: 1850, so2_kg: 920 },
      waterUsage: { annual_m3: 450000, recycling_rate_pct: 82.5, discharge_purity_pct: 98.9 },
      energyMetrics: { mwh_consumed: 110500, renewable_pct: 55.0, cogen_heat_recovery_pct: 65.0 },
      wasteOutput: { hazardous_waste_mt: 890, non_hazardous_waste_mt: 3400, landfill_diversion_pct: 91.5 },
      processes: ['proc-002', 'proc-003', 'proc-007', 'proc-008', 'proc-009'],
    },
    {
      id: 'fac-004',
      organizationId: 'org-apex-001',
      name: 'Apex Battery Assembly & Testing — Osaka',
      country: 'Japan',
      location: 'Kansai Industrial Coastal Zone, Osaka, Japan',
      latitude: 34.6937,
      longitude: 135.5023,
      facilityType: 'High-Density Lithium-Ion Pack Assembly & Cell Testing',
      productionCapacity: '1.2 GWh / annum',
      emissionsData: { scope1_co2e_mt: 4100, scope2_co2e_mt: 9800, scope3_co2e_mt: 62000, voc_emissions_kg: 110, nox_kg: 85 },
      waterUsage: { annual_m3: 64000, recycling_rate_pct: 91.2, discharge_purity_pct: 99.9 },
      energyMetrics: { mwh_consumed: 29000, renewable_pct: 71.0, clean_grid_cert: true },
      wasteOutput: { hazardous_waste_mt: 120, non_hazardous_waste_mt: 430, landfill_diversion_pct: 97.4 },
      processes: ['proc-004', 'proc-006', 'proc-010', 'proc-012'],
    },
  ],
  products: [
    { id: 'prod-001', organizationId: 'org-apex-001', name: 'Apex-Fluor 400 Protective Polymer', sku: 'AF400-EUR-01', category: 'Specialty Coatings', markets: ['EU', 'US', 'JP'] },
    { id: 'prod-002', organizationId: 'org-apex-001', name: 'EcoPack Ultra-Barrier Food Film', sku: 'EP-UBF-09', category: 'Circular Packaging', markets: ['EU', 'UK', 'US'] },
    { id: 'prod-003', organizationId: 'org-apex-001', name: 'PowerCell X9 High-Density Storage Pack', sku: 'PCX9-BAT-48V', category: 'Industrial Energy Storage', markets: ['EU', 'US', 'JP', 'UK'] },
    { id: 'prod-004', organizationId: 'org-apex-001', name: 'SynthoFlex High-Temp Fluoroelastomer', sku: 'SF-ELAST-22', category: 'Engineered Polymers', markets: ['EU', 'US'] },
    { id: 'prod-005', organizationId: 'org-apex-001', name: 'ThermBarrier Cryogenic Aerogel Blanket', sku: 'TBA-INSUL-01', category: 'Thermal Insulation', markets: ['EU', 'US', 'DE'] },
    { id: 'prod-006', organizationId: 'org-apex-001', name: 'CryoSeal Liquid Gasket Anaerobic Compound', sku: 'CSL-GAS-88', category: 'Industrial Adhesives & Sealants', markets: ['EU', 'BE', 'DE'] },
    { id: 'prod-007', organizationId: 'org-apex-001', name: 'PureVolt Polymeric Conductive Separator', sku: 'PVC-POLY-10', category: 'Battery Component Materials', markets: ['EU', 'JP', 'US'] },
    { id: 'prod-008', organizationId: 'org-apex-001', name: 'BioSolv Heavy Industrial Degreaser', sku: 'BS-DEGR-55', category: 'Green Solvents & Cleaners', markets: ['US', 'EU', 'UK'] },
  ],
  suppliers: [
    { id: 'supp-001', organizationId: 'org-apex-001', name: 'Tokyo ChemCorp Ltd.', country: 'Japan', certifications: ['ISO 14001', 'ISO 9001', 'EcoVadis Gold'], complianceStatus: 'COMPLIANT', riskScore: 12.5 },
    { id: 'supp-002', organizationId: 'org-apex-001', name: 'BASF SE Specialty Monomers', country: 'Germany', certifications: ['ISO 14001', 'EMAS', 'TfS Together for Sustainability'], complianceStatus: 'COMPLIANT', riskScore: 8.0 },
    { id: 'supp-003', organizationId: 'org-apex-001', name: 'Nordic Bio-Polymers AB', country: 'Sweden', certifications: ['ISCC PLUS', 'FSC Certified', 'ISO 50001'], complianceStatus: 'COMPLIANT', riskScore: 6.2 },
    { id: 'supp-004', organizationId: 'org-apex-001', name: 'Rio Tinto Battery Materials Corp.', country: 'Australia', certifications: ['IRMA Verified', 'ISO 14001'], complianceStatus: 'UNDER_REVIEW', riskScore: 28.4 },
    { id: 'supp-005', organizationId: 'org-apex-001', name: 'Solvay Specialty Chemicals Belgium', country: 'Belgium', certifications: ['ISO 14001', 'Responsible Care'], complianceStatus: 'COMPLIANT', riskScore: 14.1 },
    { id: 'supp-006', organizationId: 'org-apex-001', name: 'Shin-Etsu Specialty Silicones', country: 'Japan', certifications: ['ISO 14001', 'Sony Green Partner'], complianceStatus: 'COMPLIANT', riskScore: 10.5 },
    { id: 'supp-007', organizationId: 'org-apex-001', name: 'Formosa Advanced Petrochemicals', country: 'Taiwan', certifications: ['ISO 9001'], complianceStatus: 'HIGH_RISK', riskScore: 54.0 },
    { id: 'supp-008', organizationId: 'org-apex-001', name: 'DuPont Industrial Fluoromaterials', country: 'United States', certifications: ['ISO 14001', 'Responsible Care'], complianceStatus: 'UNDER_REVIEW', riskScore: 35.8 },
    { id: 'supp-009', organizationId: 'org-apex-001', name: 'Umicore Cathode Refining NV', country: 'Belgium', certifications: ['RMI Conflict Free', 'ISO 14001', 'EcoVadis Platinum'], complianceStatus: 'COMPLIANT', riskScore: 7.2 },
    { id: 'supp-010', organizationId: 'org-apex-001', name: 'LG Energy Materials South Korea', country: 'South Korea', certifications: ['ISO 14001', 'RE100 Signatory'], complianceStatus: 'COMPLIANT', riskScore: 15.0 },
    { id: 'supp-011', organizationId: 'org-apex-001', name: 'Air Liquide Industrial Gases SA', country: 'France', certifications: ['ISO 14001', 'ISO 50001'], complianceStatus: 'COMPLIANT', riskScore: 5.5 },
    { id: 'supp-012', organizationId: 'org-apex-001', name: 'Stora Enso Circular Packaging Solutions', country: 'Finland', certifications: ['PEFC', 'FSC Chain of Custody', 'EU Ecolabel'], complianceStatus: 'COMPLIANT', riskScore: 4.8 },
  ],
  processes: [
    { id: 'proc-001', name: 'Fluoropolymer Heat Curing & Sintering', description: 'Thermal treatment of fluoropolymer matrix at 380°C in inert nitrogen atmosphere to establish cross-linking.', inputs: ['Fluoro-dispersions', 'Nitrogen 99.99%'], chemicals: ['Perfluoroalkyl precursors', 'Ammonium salt surfactant'], emissions: ['Trace VOC', 'CO2 heat loss'], waste: ['Filter particulate cake'], energyKw: 450.0 },
    { id: 'proc-002', name: 'Acid Leaching & Neutralization', description: 'Hydrometallurgical extraction and subsequent neutralization of reactive salts in wet scrubbers.', inputs: ['Sulfuric Acid 98%', 'Sodium Hydroxide 50%'], chemicals: ['H2SO4', 'NaOH', 'Calcium hydroxide'], emissions: ['Scrubber water vapor'], waste: ['Neutralized Gypsum Sludge (non-haz)'], energyKw: 120.0 },
    { id: 'proc-003', name: 'Solvent Recovery & Multi-Stage Distillation', description: 'Vacuum distillation cycle recovering 98.5% of isopropyl alcohol and ethyl acetate solvents.', inputs: ['Spent solvent stream'], chemicals: ['Isopropanol', 'Ethyl Acetate', 'Toluene traces'], emissions: ['Condenser vent off-gas (abated)'], waste: ['Still bottom distillation residue'], energyKw: 880.0 },
    { id: 'proc-004', name: 'Cathode Slurry Mixing & Ultrasonic Dispersal', description: 'Homogenization of NMC cathode active material, carbon black, and PVDF binder in NMP.', inputs: ['NMC Powder', 'Carbon Black', 'NMP solvent'], chemicals: ['N-Methyl-2-pyrrolidone (CAS 872-50-4)'], emissions: ['NMP vapor captured via condenser'], waste: ['Scraper residue'], energyKw: 310.0 },
    { id: 'proc-005', name: 'High-Pressure Bio-Resin Extrusion', description: 'Twin-screw compounding and continuous extrusion of PLA/PHA biocomposite films.', inputs: ['Bio-PLA Pellets', 'Cellulose nanofibrils'], chemicals: ['Citric acid plasticizer'], emissions: ['Negligible bio-steam'], waste: ['Extruder purge trimmings (recycled)'], energyKw: 560.0 },
    { id: 'proc-006', name: 'Plasma Surface Activation & Corona Discharge', description: 'Atmospheric pressure dielectric barrier discharge modifying surface polarity for bonding.', inputs: ['High-voltage electrical power', 'Compressed dry air'], chemicals: ['Ozone (catalytically destroyed)'], emissions: ['De-ozonized exhaust'], waste: ['None'], energyKw: 85.0 },
    { id: 'proc-007', name: 'Nitrogen Blanket Chemical Synthesis', description: 'Closed-vessel organic synthesis of elastomeric precursors under pressurized N2 blanketing.', inputs: ['Monomer batch', 'Polymerization initiator'], chemicals: ['Organic peroxides', 'Specialty amines'], emissions: ['Rupture disc vent to flare stack'], waste: ['Cleaning rinse water'], energyKw: 240.0 },
    { id: 'proc-008', name: 'Regenerative Thermal Oxidation (RTO)', description: 'Ceramic bed heat exchange oxidizing volatile organics at 850°C with 99.5% destruction efficiency.', inputs: ['Facility exhaust duct gas'], chemicals: ['Methane assist fuel'], emissions: ['CO2', 'H2O vapor', 'Ultra-low NOx'], waste: ['Spent ceramic media (annual)'], energyKw: 1100.0 },
    { id: 'proc-009', name: 'Wastewater Heavy Metal Precipitation', description: 'Chemical reduction, sulfide precipitation, and clarifier settling for heavy metals removal.', inputs: ['Industrial effluent'], chemicals: ['Ferric chloride', 'Sodium dimethyldithiocarbamate'], emissions: ['None'], waste: ['Dewatered metal hydroxide cake'], energyKw: 95.0 },
    { id: 'proc-010', name: 'Supercritical CO2 Precision Cleansing', description: 'Extraction of trace oils and microscopic contaminants from precision battery tabs using SC-CO2.', inputs: ['Liquid CO2', 'Chamber pressure 100 bar'], chemicals: ['Carbon dioxide (re-liquefied)'], emissions: ['Closed loop recycling 96%'], waste: ['Extracted hydrocarbon residue'], energyKw: 180.0 },
    { id: 'proc-011', name: 'Continuous Vulcanization & Post-Cure Oven', description: 'Hot-air vulcanization tunnel followed by secondary degassing post-cure at 200°C for 4 hours.', inputs: ['Green extruded elastomer'], chemicals: ['Silane crosslinkers', 'Zinc oxide'], emissions: ['Oven exhaust to carbon filters'], waste: ['Flash trimmings'], energyKw: 620.0 },
    { id: 'proc-012', name: 'Automated Cylindrical Cell Laser Tab Welding', description: 'Fiber laser welding of nickel-plated copper busbars onto battery cell terminals.', inputs: ['Cells', 'Copper busbars', 'Laser optical line'], chemicals: ['None'], emissions: ['Laser fume extractor dust'], waste: ['HEPA dust filter'], energyKw: 75.0 },
    { id: 'proc-013', name: 'Bio-Feedstock Enzymatic Polymerization', description: 'Low-temperature catalytic conversion of plant starches into packaging polyesters.', inputs: ['Agricultural starch syrup', 'Enzyme cocktails'], chemicals: ['Enzyme biocatalyst'], emissions: ['Biogenic CO2'], waste: ['Spent biomass cake for soil amendment'], energyKw: 140.0 },
    { id: 'proc-014', name: 'VOC Carbon Bed Adsorption & Desorption', description: 'Dual-canister activated carbon filter bank removing chlorinated and fluorinated VOCs.', inputs: ['Process exhaust'], chemicals: ['Granular activated carbon'], emissions: ['Clean air discharge < 1 ppm VOC'], waste: ['Spent carbon for thermal regeneration'], energyKw: 190.0 },
    { id: 'proc-015', name: 'Pyrolysis Char Gasification & Heat Recovery', description: 'High-temperature thermal cracking of waste plastic scrap generating synthesis fuel gas.', inputs: ['Internal production plastic scrap'], chemicals: ['Synthetic syngas'], emissions: ['Clean flue gas to heat recovery boiler'], waste: ['Inert ash residue'], energyKw: 750.0 },
  ],
};
